name: Test with action

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 10
      - run: yarn install
      - run: yarn test
      - run: yarn test:lint
      - name: Run Jest
        uses: stefanoeb/jest-action@1.0.0