name: Parallel on every OS FF
on: [push]
jobs:
  run-firefox:
    name: every OS ff
    runs-on: ubuntu-16.04
    container: cypress/browsers:node12.13.0-chrome78-ff70
      # Cypress Docker image with Chrome v78
      # and Firefox v70 pre-installed
#    strategy:
#      matrix:
#        # run 2 copies of the current job in parallel
#        # and they will load balance all specs
#        os: ['macos-latest']
#        machines: [1]
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      # because of "record" and "parallel" parameters
      # these containers will load balance all found tests among themselves
      - name: run tests
        uses: cypress-io/github-action@v1
        timeout-minutes: 10

        with:
          browser: firefox
          record: true
          parallel: true
          group: Parallel 2x ff on ${{ matrix.os }}
          # on Mac and Linux we can use "npm start"
          start: yarn tff
          # but for this particular project on Windows we need a different start command
#          start-windows: npm run start:ci:windows
        env:
          # pass the Dashboard record key as an environment variable
          CYPRESS_RECORD_KEY: "0993effe-ab74-442e-97a0-99d15dbfd6b4"